---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.caseui.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.caseui.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.caseui.name }}
    spec:
      containers:
      - image: {{ .Values.caseui.image.repository }}:{{ .Values.caseui.image.tag }}
        name: {{ .Values.caseui.name }}
        resources:
          # requests:
          #   memory: {{ .Values.resources.min.memory.default }}
          #   cpu: {{ .Values.resources.min.cpu.default }}
          limits:
            memory: {{ .Values.resources.max.memory.default }}
            # cpu: {{ .Values.resources.max.cpu.default }}         
        envFrom:
        - configMapRef:
            name: {{ .Values.caseui.image.configMapRef }}
        ports:
        - containerPort: {{ .Values.caseui.service.port }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}



---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.caseui.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.caseui.service.type }}
  ports:
  - port: {{ .Values.caseui.service.port }}
  selector:
    name: {{ .Values.caseui.name }}
