---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.coreui.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.coreui.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.coreui.name }}
    spec:
      containers:
      - image: {{ .Values.coreui.image.repository }}:{{ .Values.coreui.image.tag }}
        name: {{ .Values.coreui.name }}
        resources:
          # requests:
          #   memory: {{ .Values.resources.min.memory.default }}
          #   cpu: {{ .Values.resources.min.cpu.default }}
          limits:
            memory: {{ .Values.resources.max.memory.default }}
            # cpu: {{ .Values.resources.max.cpu.default }}         
        envFrom:
        - configMapRef:
            name: {{ .Values.coreui.image.configMapRef }}
        ports:
        - containerPort: {{ .Values.coreui.service.port }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/tenants
          name: tenant-config        
      volumes:
      - name: tenant-config
        configMap:
          # name: awgment-admin-configmap
          name: tenant-config
         
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}



---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.coreui.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.coreui.service.type }}
  ports:
  - port: {{ .Values.coreui.service.port }}
  selector:
    name: {{ .Values.coreui.name }}
