apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-augmnt
#  namespace: sandbox
spec:
  isCA: true
  commonName: local-augmnt
  secretName: local-augmnt
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
#---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: letsencrypt-ca
#   namespace: sandbox
# spec:
#   ca:
#     secretName: letsencrypt-ca

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: augmnt-local
# spec:
#   secretName: augmnt-local
#   dnsNames:
#   - "*.172.17.0.1.nip.io"
#   issuerRef:
#     name: selfsigned-issuer