---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "postgres"
spec:
  ports:
    -
      name: "postgres"
      protocol: "TCP"
      port: 5432
      targetPort: 5432
      nodePort: 0
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "postgres"
subsets:
  -
    addresses:
      -
        ip: "192.168.1.46"
    ports:
      -
        port: 5432
        name: "postgres"
