replicaCount: 1
namespace: default
imagePullSecrets: ts-nexus 
imagePullPolicy: Always
configMapRef: augmnt-env

coreui:
  name: core-ui
  image:
    repository: techsophyofficial/awgment-ui-core
    tag: v0.1.0-beta
    configMapRef: ui-env
  service:
    type: ClusterIP
    port: 80
    
formmodeler:
  name: form-modeler
  image:
    repository: techsophyofficial/awgment-modeler-form
    tag: v0.1.0-beta
    configMapRef: ui-env    
  service:
    type: ClusterIP
    port: 80
    
rulemodeler:
  name: rule-modeler
  image:
    repository: techsophyofficial/awgment-modeler-rule
    tag: v0.1.0-beta
    configMapRef: ui-env  
  service:
    type: ClusterIP
    port: 80 

workflowmodeler:
  name: workflow-modeler
  image:
    repository: techsophyofficial/awgment-modeler-workflow
    tag: v0.1.0-beta
    configMapRef: ui-env  
  service:
    type: ClusterIP
    port: 80
    
accountui:
  name: account-ui
  image:
    repository: techsophyofficial/awgment-ui-account
    tag: v0.1.0-beta
    configMapRef: ui-env
  service:
    type: ClusterIP
    port: 80

caseui:
  name: case-ui
  image:
    repository: techsophyofficial/awgment-ui-case
    tag: v0.1.0-beta
    configMapRef: ui-env
  service:
    type: ClusterIP
    port: 80



configserver:
  name: cloud-config-server
  image:
    repository: techsophyofficial/awgment-cloud-config-server
    tag: v0.1.0-beta
    configMapRef: augmnt-env  
  service:
    type: ClusterIP
    port: 8080         

gateway:
  name: gateway
  image:
    repository: techsophyofficial/awgment-api-gateway
    tag: v0.1.0-beta
    configMapRef: augmnt-env
    applicationfile: applicationfile   
  service:
    type: ClusterIP
    port: 8080
  url: http://gateway:8080/api


formapp:
  name: form-app
  image:
    repository: techsophyofficial/awgment-app-form
    tag: v0.1.0-beta
    configMapRef: augmnt-env  
  service:
    type: ClusterIP
    port: 8080         

ruleapp:
  name: rule-app
  image:
    repository: techsophyofficial/awgment-app-rule
    tag: v0.1.0-beta
    configMapRef: augmnt-env  
  service:
    type: ClusterIP
    port: 8080
    
workflowapp:
  name: workflow-app
  image:
    repository: techsophyofficial/awgment-app-workflow
    tag: v0.1.0-beta
    configMapRef: augmnt-env   
  service:
    type: ClusterIP
    port: 8080
    
accountapp:
  name: account-app
  image:
    repository: techsophyofficial/awgment-app-account
    tag: v0.1.0-beta
    configMapRef: augmnt-env   
  service:
    type: ClusterIP
    port: 8080
    accountapp:
  maxFileSize: 20MB
  registration:
    failSubject: "User Registration Failed"
    email: 
  clients: "camunda-identity-service,ticketing-system"
  emailValidity: 86400

uxappcontroller:
  name: uxapp-controller
  image:
    repository: techsophyofficial/awgment-app-ux-controller
    tag: v0.1.0-beta
    configMapRef: augmnt-env
  service:
    type: ClusterIP
    port: 8080         

workflowengine:
  name: workflow-engine
  image:
    repository: techsophyofficial/awgment-workflow-engine
    tag: v0.1.0-beta
    configMapRef: augmnt-env   
  service:
    type: ClusterIP
    port: 8080
    
runtimeformapp:
  name: runtime-form-app
  image:
    repository: techsophyofficial/awgment-app-runtime-form
    tag: v0.1.0-beta
    configMapRef: augmnt-env  
  service:
    type: ClusterIP
    port: 8080

ruleengine:
  name: rules
  image:
    repository: techsophyofficial/awgment-rule-engine
    tag: v0.1.0-beta
    configMapRef: augmnt-env
  service:
    type: ClusterIP
    port: 8080

utilapp:
  name: util-app
  image:
    repository: techsophyofficial/awgment-app-util
    tag: v0.1.0-beta
    configMapRef: augmnt-env
  service:
    type: ClusterIP
    port: 8080

keycloak:
   realm: techsophy-platform
   client:
      frontend: tp-ui-core
      backend: camunda-identity-service
      secret: 
   url: 
resources:
  min:
    cpu:
      default: 0.1m
    memory:
      default: 5Mi
      
  max:
    cpu:
      default:
    memory:
      default: 16Mi
      accountapp: 384Mi
      configserver: 192Mi
      formapp: 384Mi
      gateway: 256Mi
      keycloak: 256Mi
      ruleapp: 384Mi
      ruleengine: 256Mi
      runtimeformapp: 384Mi
      utilapp: 256Mi
      uxappcontroller: 256Mi
      workflowapp: 352Mi
      workflowengine: 496Mi

    
mongo:
   url: 
   transaction_enabled: true
 
cloudconfig:
   url: 
   user: 
   password: 

postgres:
     camunda:
         dburl: 
         user: 
         password: 
         database: 
   
ingress:
   name:
     keycloak: keycloak-ingress
     gateway: gateway-ingress
     tsffrontend: tsf-ingress
     camunda: camunda-ingress
   class:
     nginx: nginx
     alb: alb
   clusterissuer:
     issuer: 
     dev: 
     uat: 
     prod:   
   hosts:
     keycloak: 
     gateway: 
     tsffrontend: 
     camunda: 
   urls:
     keycloak: 
     gateway: 
     tsffrontend:  
     camunda: 
   secretname:
     keycloak: 
     gateway: 
     tsffrontend: 
     camunda: 


templatemodeler:
   name: template-modeler
   image:
     repository: nexus.techsophy.com/augmnt/template-modeler
     tag: 2.0-RC1
     configMapRef:
   service:
     type: ClusterIP
     port: 80

casemodeler:
   name: case-modeler
   image:
     repository: nexus.techsophy.com/augmnt/case-modeler
     tag: 2.0-RC1
     configMapRef:
   service:
     type: ClusterIP
     port: 80

checklistmodeler:
   name: checklist-modeler
   image:
     repository: nexus.techsophy.com/augmnt/checklist-modeler
     tag: 2.0-RC1
     configMapRef:
   service:
     type: ClusterIP
     port: 80

adminui:
   name: admin-ui
   image:
     repository: nexus.techsophy.com/augmnt/admin-ui
     tag: 2.0-RC1
     configMapRef:
   service:
     type: ClusterIP
     port: 80
   
templateapp:
   name: template-app
   image:
     repository: nexus.techsophy.com/augmnt/templates-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080
    
notificationapp:
   name: tp-app-notification
   image:
     repository: nexus.techsophy.com/augmnt/notification-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

dmsapp:
   name: dms-app
   image:
     repository: nexus.techsophy.com/augmnt/dms-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

documentconverterapp:
   name: document-converter
   image:
     repository: nexus.techsophy.com/augmnt/documentconverter-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

pdfconvertor:
   name: tp-pdf-convertor
   image:
     repository: nexus.techsophy.com/augmnt/pdf-convertor
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

caseapp:
   name: case-app
   image:
     repository: nexus.techsophy.com/augmnt/case-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

adminapp:
   name: admin-app
   image:
     repository: nexus.techsophy.com/augmnt/admin-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

pciapp:
   name: pci-app
   image:
     repository: nexus.techsophy.com/augmnt/pci-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

elasticsearchapp:
   name: tp-elastic-search-app
   image:
     repository: nexus.techsophy.com/augmnt/elasticsearch-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080
    
checklistengine:
   name: checklist-engine
   image:
     repository: nexus.techsophy.com/augmnt/checklist-engine
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

checklistapp:
   name: checklist-app
   image:
     repository: nexus.techsophy.com/augmnt/checklist-app
     tag: 2.0-RC1
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080
