namespace: default
accountapp:
  registration:
    email: "noreply-tsf@techsophy.com"

keycloak:
  db:
    host: postgres:5432
    name: keycloakdb
    password: password
    user: vaibhav
    vendor: postgres
  adminUser: admin
  adminPassword: Admin@^&%$
  client:
    secret: 0ef502e1-567a-48cf-ae56-7e1a5bdfe3c4
  url: http://192.168.1.101:8888
  # clientURL: http://192.168.1.101:8888


gateway:
  name: gateway
  image:
    repository: localhost:5001/augmnt/api-gateway
    tag: 2.0-RC1
    configMapRef: augmnt-env
    applicationfile: applicationfile   
  service:
    type: ClusterIP
    port: 8080
  url: http://gateway:8080/api



mongo:
   url: mongodb://mongo:27017/?retryWrites=false
   transaction_enabled: false
postgres:
     camunda:
         dburl: jdbc:postgresql://postgres:5432/camunda
         user: vaibhav
         password: password
         database: camunda
cloudconfig:
   url: https://git.techsophy.com/techsophy-platform/tp-cloud-config.git
   user: gitlabuser
   password: Change#1234


ingress:
   clusterissuer:
     issuer: selfsigned-issuer
    #  dev: letsencrypt-dev
    #  uat: letsencrypt-staging
    #  prod: letsencrypt-prod  
   hosts:
     keycloak: auth.172.17.0.1.nip.io
     gateway: api.172.17.0.1.nip.io
     tsffrontend: awgment.172.17.0.1.nip.io
     camunda: camunda.172.17.0.1.nip.io
   secretname:
     keycloak: local-augmnt
     gateway: local-augmnt
     tsffrontend: local-augmnt
     camunda: local-augmnt
