namespace: default
accountapp:
  registration:
    email: "noreply-tsf@techsophy.com"

keycloak:
  name: keycloak
  image:
    repository: localhost:5001/augmnt/keycloak
    tag: latest
    configMapRef: keycloak-env
  service:
    type: ClusterIP
    port: 8080
  realm: techsophy-platform
  db:
    host: postgres:5432
    name: keycloakdb
    password: password
    user: vaibhav
    vendor: postgres
  adminUser: admin
  adminPassword: Admin@^&%$
  client:
    forntend: tp-ui-core
    backend: camunda-identity-service
    secret: 7f74d270-073f-460d-958e-7824c1316366
  url: http://keycloak:8080
  clientURL: https://auth.172.17.0.1.nip.io:8443


gateway:
  name: gateway
  image:
    repository: localhost:5001/augmnt/api-gateway
    tag: 2.0-RC1
    configMapRef: augmnt-env
    applicationfile: applicationfile   
  service:
    type: ClusterIP
    port: 8080
  url: http://gateway:8080/api

coreui:
  name: core-ui
  image:
    repository: localhost:5001/augmnt/coreui
    tag: latest
    configMapRef:  ui-env
  service:
    type: ClusterIP
    port: 80

mongo:
   url: mongodb://mongo:27017/
postgres:
     camunda:
         dburl: jdbc:postgresql://postgres:5432/camunda
         user: vaibhav
         password: password
         database: camunda
cloudconfig:
   url: https://github.com/TechsophyOfficial/tp-cloud-config.git
   user: test
   password: test


ingress:
   clusterissuer:
     issuer: selfsigned-issuer
    #  dev: letsencrypt-dev
    #  uat: letsencrypt-staging
    #  prod: letsencrypt-prod  
   hosts:
     keycloak: auth.172.17.0.1.nip.io
     gateway: api.172.17.0.1.nip.io
     tsffrontend: awgment.172.17.0.1.nip.io
     camunda: camunda.172.17.0.1.nip.io
   secretname:
     keycloak: local-augmnt
     gateway: local-augmnt
     tsffrontend: local-augmnt
     camunda: local-augmnt
