namespace: default
accountapp:
  registration:
    email: "noreply-tsf@gmail.com"
keycloak:
  adminUser: admin
  adminPassword: Admin@^&%$
  client:
    secret: 0ef502e1-567a-48cf-ae56-7e1a5bdfe3c4
  db:
    host: <POSTGRES_HOST>:<POSTGRES:PORT> 
    user: <POSTGRES_USER>
    password: <POSTGRES_PASSWORD>
    name: keycloakdb
    vendor: postgres
  url: http://<you ip like 192.168.1.16>:8888


mongo:
    url: mongodb+srv://<username>:<password>@<mongo.cluster.com>:27017/?retryWrites=true
postgres:
  camunda:
     dburl: jdbc:postgresql://<POSTGRES_HOST>:<POSTGRES:PORT>/camundadb
     user: postgres
     password: password
     database: camundadb




cloudconfig:
  url: https://github.com/TechsophyOfficial/tp-cloud-config.git
  user: test
  password: test


ingress:
#  clusterissuer:
#    issuer: selfsigned-issuer
    #  dev: letsencrypt-dev
    #  uat: letsencrypt-staging
    #  prod: letsencrypt-prod
  hosts:
    keycloak: awgment.172.17.0.1.nip.io
    gateway: awgment.172.17.0.1.nip.io
    tsffrontend: awgment.172.17.0.1.nip.io
    camunda: awgment.172.17.0.1.nip.io
  urls:
    scheme: http
    port: 8080
#    scheme: http
#    port: 8080
    keycloak: http://<you ip like 192.168.1.16>:8888/
#    gateway: http://api.172.17.0.1.nip.io:8080
#    tsffrontend: http://awgment.172.17.0.1.nip.io:8080
#    camunda:  http://camunda.172.17.0.1.nip.io:8080/camunda
  secretname:
    keycloak: awgment-certificate
    gateway: awgment-certificate
    tsffrontend: awgment-certificate
    camunda: awgment-certificate
