namespace: default
accountapp:
  registration:
    email: "noreply-tsf@techsophy.com"

keycloak:
  image:
    repository: localhost:5001/augmnt/keycloak
    tag: latest
  db:
    name: Keyclaokdba
    password: postgres
    user: postgres
    vendor: postgres
  adminUser: admin
  adminPassword: Admin@^&%$
  client:
    secret: 7f74d270-073f-460d-958e-7824c1316366
  url: http://keycloak:8080
  clientURL: http://keycloak:8080


gateway:
  image:
    repository: localhost:5001/awgment-api-gateway
    tag: latest
  url: http://gateway:8080/api

coreui:
  image:
    repository: localhost:5001/augmnt/coreui
    tag: latest


mongo:
   url: mongodb://mongo:27017/
postgres:
     camunda:
         dburl: jdbc:postgresql://postgres:5432/camunda
         user: postgres
         password: postgres
         database: camundadb
cloudconfig:
   url: https://github.com/TechsophyOfficial/tp-cloud-config.git
   user: test
   password: test


ingress:
   clusterissuer:
     issuer: selfsigned-issuer
    #  dev: letsencrypt-dev
    #  uat: letsencrypt-staging
    #  prod: letsencrypt-prod  
   hosts:
     keycloak: keycloak
     gateway: api.172.17.0.1.nip.io
     tsffrontend: awgment.172.17.0.1.nip.io
     camunda: camunda.172.17.0.1.nip.io
   secretname:
     keycloak: local-augmnt
     gateway: local-augmnt
     tsffrontend: local-augmnt
     camunda: local-augmnt
