---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.workflowengine.image.configMapRef }}
  namespace: {{ .Values.namespace }}
data:
  GATEWAY_URI: {{ .Values.gateway.url }}
  JDBC_PASSWORD: {{ .Values.postgres.camunda.password }}
  JDBC_URL: {{ .Values.postgres.camunda.dburl }}
  JDBC_USER: {{ .Values.postgres.camunda.user }}
  KEYCLOAK_CLIENT_ID: {{ .Values.keycloak.client.backend }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.client.secret }}
  KEYCLOAK_REALM_NAME: {{ .Values.keycloak.realm }}
  KEYCLOAK_URL_AUTH: {{ .Values.keycloak.url }}
  KEYCLOAK_URL_PLUGIN: {{ .Values.keycloak.url }}
  KEYCLOAK_URL_TOKEN: {{ .Values.keycloak.url }}
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workflowengine.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.workflowengine.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.workflowengine.name }}
    spec:
      containers:
      - image: {{ .Values.workflowengine.image.repository }}:{{ .Values.workflowengine.image.tag }}
        name: {{ .Values.workflowengine.name }}
        envFrom:
        - configMapRef:
            name: {{ .Values.workflowengine.image.configMapRef }}
        ports:
        - containerPort: {{ .Values.workflowengine.service.port }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}



---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workflowengine.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.workflowengine.service.type }}
  ports:
  - port: {{ .Values.workflowengine.service.port }}
  selector:
    name: {{ .Values.workflowengine.name }}
