replicaCount: 1
namespace: dev
imagePullSecrets: ts-nexus 
imagePullPolicy: Always
configMapRef: augmnt-env


keycloak:
  name: keycloak
  adminUser: admin
  adminPassword:
  image:
    repository: techsophyofficial/awgment-keycloak
    tag: v0.1.0-beta
    configMapRef: keycloak-env
  service:
    type: ClusterIP
    port: 8080
  realm: techsophy-platform
  db:
    host: postgres:5432
    name: keycloakdb
    password: 
    user: 
    vendor: postgres

  

ingress:
   name:
     keycloak: keycloak-ingress
   class:
     nginx: nginx
     alb: alb
   clusterissuer:
     issuer: 
   hosts:
     keycloak:
   secretname:
     keycloak:
