apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.coreui.image.configMapRef }}
  namespace: {{ .Values.namespace }}
data:
  HOSTNAME: "awgment.172.17.0.1.nip.io"
  WEB_ROOT: "/usr/share/nginx/html"
  REACT_baseUrL: "https://awgment.172.17.0.1.nip.io:8443"
  REACT_apiGatewayUrl: "https://api.172.17.0.1.nip.io:8443/api"
  REACT_keyCloakUrl: "https://auth.172.17.0.1.nip.io:8443/"
  REACT_keyCloakRealm: "techsophy-platform"
  REACT_keyCloakClientId: "tp-ui-core"
  REACT_publicUrl: "/model"
  REACT_socketUrl: "https://sxp.channel-adapter.k8s.techsophy.com/"
  REACT_socketPath: "/socket.io/"
  REACT_chatFileServerUrl: "https://fileserver.techsophy.com/"
  REACT_sxpProjectId: "6233029bfd9468494f68af33"