apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.coreui.image.configMapRef }}
  namespace: {{ .Values.namespace }}
data:
  HOSTNAME: "awgment.172.17.0.1.nip.io"
  WEB_ROOT: "/usr/share/nginx/html"
  baseUrL: "https://awgment.172.17.0.1.nip.io:8443"
  apiGatewayUrl: "https://api.172.17.0.1.nip.io:8443/api"
  keyCloakUrl: "https://auth.172.17.0.1.nip.io:8443/"
  keyCloakRealm: "techsophy-platform"
  keyCloakClientId: "tp-ui-core"
  publicUrl: "/model"
  socketUrl: "https://sxp.channel-adapter.k8s.techsophy.com/"
  socketPath: "/socket.io/"
  chatFileServerUrl: "https://fileserver.techsophy.com/"
  sxpProjectId: "6233029bfd9468494f68af33"