apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.coreui.image.configMapRef }}
  namespace: {{ .Values.namespace }}
data:
  HOSTNAME: {{ .Values.ingress.hosts.gateway }}
  WEB_ROOT: "/usr/share/nginx/html"

  {{- if .Values.ingress.urls.tsffrontend }}
  REACT_baseUrL: {{ .Values.ingress.urls.tsffrontend }}
  REACT_baseUrl: {{ .Values.ingress.urls.tsffrontend }}
  {{- else }}
  REACT_baseUrL: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.tsffrontend }}:{{ .Values.ingress.urls.port }}
  REACT_baseUrl: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.tsffrontend }}:{{ .Values.ingress.urls.port }}
  {{- end }}

  {{- if .Values.ingress.urls.gateway }}
  REACT_apiGatewayUrl: {{ .Values.ingress.urls.gateway }}/api
  REACT_swaggerUrl: {{ .Values.ingress.urls.gateway }}
  {{- else }}
  REACT_apiGatewayUrl: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.gateway }}:{{ .Values.ingress.urls.port }}/api
  REACT_swaggerUrl: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.gateway }}:{{ .Values.ingress.urls.port }}
  {{- end }}

  {{- if .Values.ingress.urls.camunda }}
  REACT_workflowEngineURL: {{ .Values.ingress.urls.camunda  }}
  REACT_appServerURL: {{ .Values.ingress.urls.camunda  }}/engine-rest
  {{- else }}
  REACT_workflowEngineURL: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.camunda }}:{{ .Values.ingress.urls.port }}
  REACT_appServerURL: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.camunda }}:{{ .Values.ingress.urls.port }}/engine-rest
  {{- end }}

  {{- if .Values.ingress.urls.keycloak }}
  REACT_keyCloakUrl: {{ .Values.ingress.urls.keycloak }}
  {{- else }}
  REACT_keyCloakUrl: {{ .Values.ingress.urls.scheme }}://{{ .Values.ingress.hosts.keycloak }}:{{ .Values.ingress.urls.port }}
  {{- end }}
  REACT_keyCloakRealm: {{ .Values.keycloak.realm }}
  REACT_keyCloakClientId: {{ .Values.keycloak.client.frontend }}

  REACT_publicUrl: "/model"

  REACT_publicAccountsUrl: "/accounts/"
  REACT_mfeAccountContainerBaseName: "/model/accounts" 
  REACT_publicCaseUrl: "/case-inbox/"
  REACT_publicUrlUiCase: "/case-inbox/"
  REACT_mfeContainerBasename: "/model/caseInbox"

  REACT_socketUrl: "https://sxp.channel-adapter.k8s.techsophy.com/"
  REACT_socketPath: "/socket.io/"
  REACT_chatFileServerUrl: "https://fileserver.techsophy.com/"
  REACT_sxpProjectId: "6233029bfd9468494f68af33"
  REACT_customApiServerUrl: "http://139.59.80.134:8082/process-integration/service/1.0.0"
  REACT_contextEngineApiUrl: "http://ce.test.sxp.techsophy.com/engine"

  REACT_publicFormUrl: "/model/forms/"
  REACT_mfeFormContainerBaseName: "/model/form-modeler"
  REACT_publicRulesUrl: "/model/rules/"

  REACT_publicProcessUrl: "/model/process/"

