apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name.camunda }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 120m
    nginx.ingress.kubernetes.io/proxy-redirect-to: "{{.Values.ingress.urls.scheme}}://{{ .Values.ingress.hosts.camunda }}:{{.Values.ingress.urls.port}}/"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "{{.Values.ingress.urls.scheme}}://{{ .Values.ingress.hosts.camunda }}/"
spec:
  {{- if eq .Values.ingress.urls.scheme "https" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.camunda }}
    secretName: {{ .Values.ingress.secretname.camunda }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.camunda }}
    http:
      paths:
      - path: /camunda
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.workflowengine.name }}
            port:
              number: {{ .Values.workflowengine.service.port }}