replicaCount: 1
imagePullSecrets: ts-nexus 
imagePullPolicy: Always
configMapRef: awgmnt-addon-env
    
keycloak:
   realm: techsophy-platform
   client:
      frontend: tp-ui-core
      backend: camunda-identity-service
      secret: 
   url: 
gateway:
  url: http://gateway:8080/api
      
mongo:
   url: 
   transaction_enabled: true
 
cloudconfig:
   url: 
   user: 
   password: 

smtp:
  host: smtp.gmail.com
  password: 
  port: "587"
  user: noreply.tsf@gmail.com

sns:
  access_key: 
  region: ap-south-1
  secret_key: 
  topic_arn: 

aws: 
  region: ap-south-1
  access_key: 
  access_secret: 
  bucket_name: techsophy-platform
ses:
  aws_region: ap-south-1
  access_key: 
  access_secret: 

digital_ocean:
  access_key: 
  region: sgp1
  bucket_name: augmnt
  endpoint: 
  secret_key: 

  
firebase:
  project_id: 
  private_key_id: 
  private_key: |
    -----BEGIN PRIVATE KEY-----
    z1EuHpjE6g==
    -----END PRIVATE KEY-----
  client_email: firebase-adminsdk-zdtus@kims-rn.iam.gserviceaccount.com
  client_id: 
  token_url: https://oauth2.googleapis.com/token
  enabled: "true"
  app: "true"

paytm:
  merchant_id:
  merchant_key:
razorpay:
  key_id:
  key_secret:


twilio:
  msid: 
  token: 
  account_id: 


postgres:

  camunda:

    dburl:
    user:
    password:
    database:
   
ingress:
   name:
     keycloak: keycloak-ingress
     gateway: gateway-ingress
     tsffrontend: tsf-ingress
     camunda: camunda-ingress
   class:
     nginx: nginx
     alb: alb
   clusterissuer:
     issuer: 
     dev: 
     uat: 
     prod:   
   hosts:
     keycloak: 
     gateway: 
     tsffrontend: 
     camunda: 
   urls:
     keycloak: 
     gateway: 
     tsffrontend:  
     camunda: 
   secretname:
     keycloak: 
     gateway: 
     tsffrontend: 
     camunda: 
   
templateapp:
   name: template-app
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080
    
notificationapp:
   name: tp-app-notification
   image:
     repository: techsophyofficial/awgment-app-notification
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

dmsapp:
   name: dms-app
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

documentconverterapp:
   name: document-converter
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

pdfconvertor:
   name: tp-pdf-convertor
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
     configMapRef: augmnt-env
   service:
     type: ClusterIP
     port: 8080

pciapp:
   name: pci-app
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

elasticsearchapp:
   name: tp-elastic-search-app
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080
    
checklistengine:
   name: checklist-engine
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

checklistapp:
   name: checklist-app
   image:
     repository: techsophyofficial/awgment-app-checklist
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080


admin:
   name: admin-app
   image:
     repository: techsophyofficial/awgment-app-admin
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

case:
   name: case-app
   image:
     repository: techsophyofficial/awgment-app-case
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

escalationmatrix:
   name: escalation-matrix-app
   image:
     repository: techsophyofficial/awgment-app-escalation-matrix
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

scheduler:
   name: scheduler-app
   image:
     repository: techsophyofficial/awgment-app-scheduler
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

paymentgateway:
   name: payment-gateway
   image:
     repository: techsophyofficial/awgment-app-payment-gateway
     tag: v0.1.0-beta
   service:
     type: ClusterIP
     port: 8080

runtimeescalationmatrix:
    name: runtime-escalation-matrix
    image:
     repository: techsophyofficial/awgment-runtime-escalation-matrix
     tag: v0.1.0-beta
    service:
     type: ClusterIP
     port: 8080
