apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapRef }}
data:
  GATEWAY_URI: {{ .Values.gateway.url }}
  TP_MODELER_APP_MONGO_URI: {{ .Values.mongo.url }}
  JDBC_URL: {{ .Values.postgres.camunda.dburl }}
  JDBC_USER: {{ .Values.postgres.camunda.user }}
  JDBC_PASSWORD: {{ .Values.postgres.camunda.password }} 
  GIT_CONFIG_URI: {{ .Values.cloudconfig.url }}
  GIT_USERNAME: {{ .Values.cloudconfig.user }}
  GIT_PASSWORD: {{ .Values.cloudconfig.password }}
  ADD_ALLOWEDHEADER: '*'
  ADD_ALLOWEDMETHOD: '*'
  CORS_ALLOWEDORIGINS: '*'
  DMS_ENABLED: "true"
  SMTP_DEBUG: "false"
  SMTP_HOST: {{ .Values.smtp.host }}
  SMTP_PASSWORD: {{ .Values.smtp.password }}
  SMTP_PORT: "587"
  SMTP_USER: {{ .Values.smtp.user }}
  SNS_ACCESS_KEY: {{ .Values.sns.access_key }}
  SNS_REGION: {{ .Values.sns.region }}
  SNS_SECRET_KEY: {{ .Values.sns.secret_key }}
  SNS_TOPIC_ARN:  {{ .Values.sns.topic_arn }}
  TEMPLATES_ENABLED: "true"
  TWILIO_ACCOUNT_ID: {{ .Values.twilio.account_id}}
  TWILIO_MSID: {{ .Values.twilio.msid }}
  TWILIO_TOKEN: {{ .Values.twilio.token }}
  AWS_ACCESS_KEY: {{ .Values.aws.access_key | quote }}
  AWS_ENABLED: "false"
  AWS_BUCKET_NAME: {{ .Values.aws.bucket_name }}
  AWS_REGION: {{ .Values.aws.region }} 
  AWS_SECRET_KEY: {{ .Values.aws.access_secret }}
  KEYCLOAK_URL_AUTH: {{ .Values.keycloak.url }}
  KEYCLOAK_REALM_NAME: {{ .Values.keycloak.realm }}
  KEYCLOAK_CLIENT_ID: {{ .Values.keycloak.client.backend }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.keycloak.client.secret }}
  KEYCLOAK_URL_PLUGIN: {{ .Values.keycloak.url }}
  KEYCLOAK_URL_TOKEN: {{ .Values.keycloak.url }}
  CAMUNDA_ENGINE_CONTEXT_PATH: /camunda
  EMAIL_QUERY: |
    mutation SEND_EMAIL($mailMessage: MailMessage!) {
      sendMail(input: $mailMessage)
    }
  EMAIL_VALIDITY: "86400"
  OTP_VALIDITY: "180"
  # USER_REGISTRATION_FAILURE_EMAIL_SUBJECT: User Registration Failed
  # USER_REGISTRATION_FAILURE_EMAIL_TO: 
  ELASTIC_ENABLE: "true"
  ELASTIC_SOURCE: "true"
  DIGITAL_OCEAN_ACCESSKEY: {{ .Values.digital_ocean.access_key }}
  DIGITAL_OCEAN_BUCKET_NAME: {{ .Values.digital_ocean.bucket_name }}
  DIGITAL_OCEAN_ENABLED: "true"
  DIGITAL_OCEAN_ENDPOINT: {{ .Values.digital_ocean.endpoint}}
  DIGITAL_OCEAN_REGION: {{ .Values.digital_ocean.region}}
  DIGITAL_OCEAN_SECRET_KEY: {{ .Values.digital_ocean.secret_key}}
  # USERNAME: 
  # PASSWORD: 
  # CLIENT_ID: 
  # default.pagelimit: "20"
  PCI_AUDIT_FILE_ENABLED: "false"
  PCI_AUDIT_MONGO_ENABLED: "true"
  SXP_JOURNEY_BASE_URL: https://sxp-playground.journey-manager.techsophy.com/journey
  CE_DYN_JOURNEY_URL: https://ce.techsophy.com/getNextJourney
  HOST: elasticsearch
  PORT: "9200"
  PROTOCOL: http
  MAX_FILE_SIZE: 20MB
  # CLIENTS: "camunda-identity-service,ticketing-system"
  EMAIL_PROVIDER_SENDMAIL: "false"
  EMAIL_PROVIDER_SENDGRID: "false"
  EMAIL_PROVIDER_AWS_SES: "true"
  SES_AWS_REGION: {{ .Values.ses.aws_region }}
  SES_AWS_ACCESS_KEY: {{ .Values.ses.access_key }}
  SES_AWS_ACCESS_SECRET: {{ .Values.ses.access_secret }}
  FIREBASE_PRIVATE_KEY: |
    ----BEGIN----
    ankndfsdfsdfsdfsd
    ----END----
  FIREBASE_PROJECT_ID: {{ .Values.firebase.project_id }}
  FIREBASE_PRIVATE_KEY_ID: {{ .Values.firebase.private_key_id | quote }}
  FIREBASE_CLIENT_EMAIL: {{ .Values.firebase.client_email | quote}}
  FIREBASE_CLIENT_ID: {{ .Values.firebase.client_id  | quote}} 
  FIREBASE_TOKEN_URI: {{ .Values.firebase.token_url | quote}} 
  FIREBASE_ENABLED: {{ .Values.firebase.enabled  | quote}}
  FIREBASE_APP: {{ .Values.firebase.app | quote }}
